# Generated by Django 6.1 on 2026-09-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attack_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('signature', 'Signature'), ('anomaly', 'Anomaly'), ('keyword', 'Keyword')], max_length=20)),
                ('pattern', models.TextField(help_text='Regex or keyword pattern to match against input')),
                ('category', models.CharField(blank=True, help_text='e.g. Union-based, Boolean-based, Time-based', max_length=100)),
                ('risk_weight', models.PositiveIntegerField(default=10, help_text='Points added to risk score when triggered')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_value', models.TextField(help_text='The exact substring/value that matched the rule')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='attack_logs.requestlog')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='detection_rule.detectionrule')),
            ],
        ),
    ]
