# Generated by Django 6.1 on 2026-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_app_url', models.URLField(help_text='Base URL of the target app, e.g. http://localhost:5000')),
                ('mode', models.CharField(choices=[('monitoring', 'Monitoring only'), ('blocking', 'Detect and block')], default='blocking', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
