# Generated by Django 6.1 on 2026-09-15 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('cookies', models.JSONField(blank=True, null=True)),
                ('payload_snippet', models.TextField(blank=True, help_text='The specific matched/suspicious input')),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('action_taken', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], default='allowed', max_length=10)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_ip'], name='attack_logs_source__02985a_idx'), models.Index(fields=['endpoint'], name='attack_logs_endpoin_9b6cf8_idx'), models.Index(fields=['risk_level'], name='attack_logs_risk_le_30da18_idx'), models.Index(fields=['timestamp'], name='attack_logs_timesta_cbc83b_idx')],
            },
        ),
    ]
